logging:
  level: INFO
  format: '%(asctime)s - %(levelname)s - %(message)s'

constants:
  SUCCESS: 200
  FAILURE: 400
  SIMPLE: 0
  HAVERSINE: 1
  O_1: "O_1"
  O_n: "O_n"
  O_Log_n: "O_Log_n"

countries_api:
  DE:
    static: "https://consumer-api.development.dev.woltapi.com/home-assignment-api/v1/venues/home-assignment-venue-berlin/static"
    dynamic: "https://consumer-api.development.dev.woltapi.com/home-assignment-api/v1/venues/home-assignment-venue-berlin/dynamic"
  FI:
    static: "https://consumer-api.development.dev.woltapi.com/home-assignment-api/v1/venues/home-assignment-venue-helsinki/static"
    dynamic: "https://consumer-api.development.dev.woltapi.com/home-assignment-api/v1/venues/home-assignment-venue-helsinki/dynamic"
  SE:
    static: "https://consumer-api.development.dev.woltapi.com/home-assignment-api/v1/venues/home-assignment-venue-stockholm/static"
    dynamic: "https://consumer-api.development.dev.woltapi.com/home-assignment-api/v1/venues/home-assignment-venue-stockholm/dynamic"
  JP:
    static: "https://consumer-api.development.dev.woltapi.com/home-assignment-api/v1/venues/home-assignment-venue-tokyo/static"
    dynamic: "https://consumer-api.development.dev.woltapi.com/home-assignment-api/v1/venues/home-assignment-venue-tokyo/dynamic"

cities_acronym:
  helsinki: "FI"
  berlin: "DE"
  stockholm: "SE"
  tokyo: "JP"
